### ISSUE TITLE
Look at reported issues with diffs on runs over an hour

### ISSUE THREAD

**Issue by MichaelJBerk** [MichaelJBerk/Splitter#34]

**Comment by MichaelJBerk** [comment]
In the new build, this should be fixed

**Comment by pollsmor** [comment]
Hello, the issue still appears to be present. Here is a VOD of me comparing a stopwatch on Google to Splitter: https://www.twitch.tv/videos/586066438

I decided to end the highlight at my first split ~3 and a half minutes in, and by then there is already ~a 50 second time difference between the two. By the end of the run the difference is greater than 20 minutes. 

I notice that if I don't load a split file, the timer runs faster. Still not as fast as the stopwatch on Google or my phone's stopwatch app, but noticeably faster. 

I am currently running Splitter 1.0 (build 62).

**Comment by MichaelJBerk** [comment]
In a future build, I'm changing the timer code to use LiveSplitCore instead of my own custom timer, which should hopefully make the timer more accurate
